
CREATE TABLE IF NOT EXISTS __PREFIX__FLOW(
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR2(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS __PREFIX__PROGRESS(
  ID INT AUTO_INCREMENT PRIMARY KEY ,
  NAME VARCHAR2(200) NOT NULL ,
  CREATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP ,
  BEAN_NAME VARCHAR2(200) NOT NULL
);
CREATE TABLE IF NOT EXISTS __PREFIX__FLOW_PROGRESS(
  FID INT ,
  PID INT,
  CONSTRAINT ID_FLOW FOREIGN KEY (PID) REFERENCES __PREFIX__FLOW(ID),
  CONSTRAINT ID_PROGRESS FOREIGN KEY (PID) REFERENCES __PREFIX__FLOW(ID)
);
